### ISSUE TITLE
Accept GITHUB_TOKEN for authentication

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-gh-pages#16]
I just wanted to document an idea for a feature. We could add a `GITHUB_TOKEN` secret which will automatically use the token as the username, and set the password to `x-oauth-basic`.

This is possible today, however, I get the sense that most people don't realize it is an option. Providing some nice syntactic sugar to the existing username and password parameters could make this capability more accessible, since I think a token is always preferable to a username and password.

**Comment by tboerger** [comment]
A username with a token also works totally fine, that's how I'm using it because of 2fa.

**Comment by donny-dont** [comment]
@bradrydzewski one thought I've had, and you know of this but I'll write it out here, is that if we treat the drone scm connection as a server that can be hit during a build. The token could then be injected into the build step and used. This particular plugin could be a case of that. It could also work for something like a status update so that could be a plugin.

**Comment by counterbeing** [comment]
@tboerger Maybe I'm misunderstanding something, but it sounds like i can use a deploy key in place of a password. I'm trying to do so like this:

```
  - name: publish
    image: plugins/gh-pages
    settings:
      username: counterbeing
      password:
        from_secret: github_deploy_key
      pages_directory: rendered_assets
```

I've added the secret to the drone project, and i've enabled write access on the deploy key. For some reason I'm hitting this:

```log
fatal: could not read Username for 'https://github.com': No such device or address
--
484 | 2019/04/29 05:29:38 failed to push changes: exit status 128
```

Any thoughts on why that might be?

**Comment by bradrydzewski** [comment]
I have never used this particular plugin, but I can say that when using a token for git operations you need to use the token as the username, and `x-oauth-basic` as the password.

```diff
  - name: publish
    image: plugins/gh-pages
    settings:
-     username: counterbeing
-     password:
-       from_secret: github_deploy_key
+     username:
+       from_secret: github_deploy_key
+     password: x-oauth-basic
      pages_directory: rendered_assets
```

**Comment by counterbeing** [comment]
Thanks @bradrydzewski for the quick response! That still failed with the same error though.

**Comment by bradrydzewski** [comment]
I would also point out that, I believe, deployment keys can only be used to clone code. They cannot be used to push code, which is required of this plugin. Perhaps try using a personal token instead?

**Comment by counterbeing** [comment]
When adding a key there is a checkbox to enable pushing. I was sure to check it.

I think it may be that the repo is cloned via https, but needs to be uploaded via ssh to use the key. I may need to set the url to use ssh. If i figure it out i'll post again.

**Comment by bradrydzewski** [comment]
ah yes, the username and password fields are for tokens, not ssh keys. So that explains why it does not work when you pass the secret. If you want to use the plugin with an ssh key it should look something like this:

```
  - name: publish
    image: plugins/gh-pages
    settings:
      ssh_key:
        from_secret: github_deploy_key
      pages_directory: rendered_assets
```

In terms of using the ssh clone address, there is a `remote_url` option.

**Comment by amq** [comment]
@bradrydzewski this is not working for me.

Tried:
```
- name: publish  
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    ssh_key:
      from_secret: github_ssh_key
```

and:
```
- name: publish  
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    remote_url: git@github.com:org/repo.git
    ssh_key:
      from_secret: github_ssh_key
```

Tried adding the SSH key in repository and profile.

In all cases:
```
fatal: could not read Username for 'https://github.com': No such device or address
failed to push changes: exit status 128 
```

**Comment by vioao** [comment]
How to set `remote_url ` in pipelines step，it seems that it doesn't work well.

**Comment by vioao** [comment]
@bradrydzewski 
How to set remote_url in pipelines step，it seems that it doesn't work well.

**Comment by safaci2000** [comment]
If you want to use the token, all I did was set it as the value for my password secret and it work flawlessly.

Create a Github personal token, populated your environment variable where the gh_password=<TOKEN> then all I did was have something along these lines in my config.

```yaml
- name: publish
  image: plugins/gh-pages
  settings:
    username:
      from_secret: gh_username
    password:
      from_secret: gh_password
```
