### ISSUE TITLE
set git.email and git.user in yaml

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-gh-pages#7]
In some cases we may not get this information from the `drone_*` environment variables, so it would be nice to have the ability to override in the yaml:

```
pipeline:
  publish:
    image: plugins/gh-pages
    user_email: octocat@github.com
    user_name: octocat
```

We may also want to consider setting default values when these fields are blank.
