### ISSUE TITLE
ability to set basic auth username and password

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-gh-pages#8]
This plugin assumes that a netrc file exists which is not the case for public repositories. The plugin does accept an ssh key but drone will pass the plugin the git+https url.

We should therefore provide the option to authenticate with a username and password:

```
pipeline:
  publish:
    image: plugins/gh-pages
    username: octocat
    password: password
```

This gives us the ability to use a github token (for example) instead of using an ssh key, and also having to customize the remote url.
